name: Test rsync on FreeBSD

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*.yml'
      - '!.github/workflows/freebsd-build.yml'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*.yml'
      - '!.github/workflows/freebsd-build.yml'
  schedule:
    - cron: '42 8 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test rsync on FreeBSD
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Test in FreeBSD VM
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y bash autotools m4 devel/xxhash zstd liblz4 python3 archivers/liblz4 git
        run: |
          freebsd-version
          ./configure --with-rrsync -disable-zstd --disable-md2man --disable-xxhash --disable-lz4
          make
          ./rsync --version
          ./rsync-ssl --no-motd download.samba.org::rsyncftp/ || true
    - name: save artifact
      uses: actions/upload-artifact@v3
      with:
        name: freebsd-bin
        path: |
          rsync
          rsync-ssl
          rsync.1
          rsync-ssl.1
          rsyncd.conf.5
          rrsync.1
          rrsync
