name: Test rsync on Ubuntu

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*.yml'
      - '!.github/workflows/ubuntu-build.yml'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*.yml'
      - '!.github/workflows/ubuntu-build.yml'
  schedule:
    - cron: '42 8 * * *'

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test rsync on Ubuntu
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: prep
      run: |
        sudo apt-get install acl libacl1-dev attr libattr1-dev liblz4-dev libzstd-dev libxxhash-dev python3-cmarkgfm openssl
        echo "/usr/local/bin" >>$GITHUB_PATH
    - name: configure
      run: ./configure --with-rrsync
    - name: make
      run: make
    - name: install
      run: sudo make install
    - name: info
      run: rsync --version
    - name: check
      run: sudo RSYNC_EXPECT_SKIPPED=crtimes make check
    - name: check30
      run: sudo RSYNC_EXPECT_SKIPPED=crtimes make check30
    - name: check29
      run: sudo RSYNC_EXPECT_SKIPPED=crtimes make check29
    - name: ssl file list
      run: rsync-ssl --no-motd download.samba.org::rsyncftp/ || true
    - name: save artifact
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu-bin
        path: |
          rsync
          rsync-ssl
          rsync.1
          rsync-ssl.1
          rsyncd.conf.5
          rrsync.1
          rrsync
